### ISSUE TITLE
(node:1948) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by Nabiypy** [jmbl1685/socialfriends#2]
I am not able to run the start script with the following error:
<img width="738" alt="screen shot 2018-11-01 at 2 09 57 pm" src="https://user-images.githubusercontent.com/6829713/47857254-16851280-dde1-11e8-88eb-81c5efa820af.png">
PM - error: uncaughtException: ENOENT: no such file or directory, open 'logs/Log_11/1/2018.log' date=Thu Nov 01 2018 14:08:49 GMT+0000 (GMT), pid=1948, uid=501, gid=20, cwd=/Users/hanson/WebstormProjects/inextranet/server, execPath=/usr/local/Cellar/node/9.8.0/bin/node, version=v9.8.0, argv=[node, /Users/hanson/WebstormProjects/inextranet/server/index.js], rss=110055424, heapTotal=82345984, heapUsed=58479680, external=21001240, loadavg=[1.34228515625, 1.49951171875, 1.65771484375], uptime=4738, trace=[], stack=[Error: ENOENT: no such file or directory, open 'logs/Log_11/1/2018.log']

**Comment by Nabiypy** [comment]
Kindly advice

**Comment by jmbl1685** [comment]
Hello @Nabiypy , let me review to help in the correction of your error.

**Comment by jmbl1685** [comment]
@Nabiypy can get the latest version (git clone...), I disabled Winston (Logger module). I remind you that the project is not finished yet, I still have to correct many things. Good luck!!

**Comment by Nabiypy** [comment]
> @Nabiypy can get the latest version (git clone...), I disabled Winston (Logger module). I remind you that the project is not finished yet, I still have to correct many things. Good luck!!

Sure, i understand. Thank you for your support.
i appreciate the help so far.
i am learning a lot from your project right now.

Please note that when i ran the app on downgraded nodejs version 8.9.4 and npm 6.4.1 on windows environment it works fine.
i am able to post signup, sign and data persisted successfully on mlab.

Thank you.

**Comment by Nabiypy** [comment]
Awesome!

Please note that https://github.com/jmbl1685/express-restapi-es6.git is working perfectly and will use it for my current project.

**Comment by jmbl1685** [comment]
> Awesome!
> 
> Please note that https://github.com/jmbl1685/express-restapi-es6.git is working perfectly and will use it for my current project.

I'm glad. Thanks, please share it among your friends.
